= Elasticsearch
Jörg Prante
Version 6.3.2.0
:sectnums:
:toc: preamble
:toclevels: 4
:!toc-title: Content
:experimental:
:description: Elasticsearch
:keywords: Java, Search, Server, Distributed Application

== Introduction

The Elasticsearch Distributed Search application is a software to
implement the Elasticsearch server platform with essential features
in a modular fashion using current Java 10 modularization technology.

== Synopsis

The following changes have been applied to the original work

- Support og JSON format for log4j and configuration file

== Copyright

I, Jörg Prante, waive all coprights regarding this customized build of Elasticsearch
and documentation. This work is not endorsed by Elasticsearch BV.

https://creativecommons.org/publicdomain/zero/1.0/

Elasticsearch License

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
you may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Elasticsearch is a trademark of Elasticsearch BV, registered in the U.S. and in other countries.

Apache, Apache Lucene, Apache Hadoop, Hadoop, HDFS and the yellow elephant logo are trademarks of the
Apache Software Foundation in the United States and/or other countries.
