FROM fl.hbz-nrw.de/jprante/alpine-glibc-openjdk10

COPY *.tar.gz /

ARG version

RUN adduser -D -u 1000 elasticsearch && \
    tar -zxf /elasticsearch*.tar.gz && \
    mv /elasticsearch-${version} /elasticsearch && \
    chown -R elasticsearch /elasticsearch && \
    rm -f /elasticsearch*.tar.gz
